### ISSUE TITLE
[META] Page permission refactor

### ISSUE THREAD

**Issue by FinalAngel** [django-cms/django-cms#4598]
The permissions system needs an overhaul to cover edge-cases. Additionally we should think about a better UX and/or documentation.
- [ ] #4338 double click to edit
- [ ] #1430 Page permission inconsistencies
- [ ] #2321 Permissions for a large user base
- [x] #4524 Permissions issues
- [x] #4435 Rework logic in permission system
- [ ] #4322 GlobalPagePermission in the Django Admin tries to load all Django users even with CMS_RAW_ID_USERS = True
- [ ] #3732 View restriction permission confusing and poorly documented 
- [ ] #2259 Permission per language
- [ ] #3662 More granular permissions
- [ ] add working integration tests

**Comment by Aiky30** [comment]
Closing as every issue mentioned in this issue is closed or merged.
